name: build
env:
  BUILD_NAME: meilisync
  ENV_TYPE: production

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main'}}
          tags: |
            ghcr.io/vitrinagram/${{ env.BUILD_NAME }}-${{ env.ENV_TYPE }}:latest
            ghcr.io/vitrinagram/${{ env.BUILD_NAME }}-${{ env.ENV_TYPE }}:${{ github.ref_name }}-${{ steps.useful_vars.outputs.short_sha }}-${{ steps.useful_vars.outputs.timestamp }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # no-cache: true
